In [43]:
import pandas as pd
import numpy as np

df = pd.read_csv("filtered_protacs.csv")
target_proteins = np.array(list(df["Target Protein"]))
e3_targets = np.array(list(df["E3 Target"]))
warheads = np.array(list(df["Warhead"]))
linkers = np.array(list(df["Linker"]))
e3_ligands = np.array(list(df["E3 Ligand"]))
dc_50 = np.array(list(df["DC50 (nM)"]))
d_max = np.array(list(df["Dmax (%)"]))
percent_degradation = np.array(list(df["Percent degradation (%)"]))
ic_50 = np.array(list(df["IC50 (nM, Protac to Target)"]))

In [44]:
# Process dc_50 values
f= open("dc50_labels.txt", "r")
lines = f.readlines()
refined_lines = []
for l in lines:
    l = l.replace("(n/a)", "")
    l = l.replace("\n", "")
    l = l.replace(">", "")
    l = l.replace("<", "")
    l = l.replace("=", "")
    refined_lines.append(l)
print(len(refined_lines))

final_labels = []
for l in refined_lines:
    arr = l.split('/')
    if len(arr) > 1:
        smallest_so_far = 999999
        for el in arr:
            if el == "":
                continue
            if el.find("~") > 0 or el.find("-") > 0:
                continue
            el = float(el)
            if el < smallest_so_far:
                smallest_so_far = el
        final_labels.append(smallest_so_far)
    else:
        final_labels.append(arr[0])
        
dc50_indices = []
for i, val in enumerate(final_labels):
    val = str (val)
    if val == "":
        continue
    else:
        dc50_indices.append(i)
        
dc50_labels = []
for m in final_labels:
    m = str (m)
    if m == "":
        dc50_labels.append(m)
        continue
    if m.find("~") > 0:
        m.split("~")
        m = float (m[0])
        dc50_labels.append(m)
    elif m.find("-") > 0:
        m.split("-")
        m = float (m[0])
        dc50_labels.append(m)
    else:
        m = float (m)
        dc50_labels.append(m)
 

5388


In [45]:
# Dmax values
refined_d = []
for d in d_max:
    d = str (d)
    d = d.replace("(n/a)", "")
    d = d.replace("N.D.", "")
    d = d.replace("nan", "")
    d = d.replace("\n", "")
    d = d.replace(">", "")
    d = d.replace("<", "")
    d = d.replace("=", "")
    refined_d.append(d)
    
final_d = []
for d in refined_d:
    arr = d.split('/')
    if len(arr) > 1:
        smallest_so_far = 999999
        for el in arr:
            if el == "":
                continue
            if el.find("~") > 0 or el.find("-") > 0:
                continue
            el = float(el)
            if el < smallest_so_far:
                smallest_so_far = el
        final_d.append(smallest_so_far)
    else:
        final_d.append(arr[0])
        
dmax_indices = []
for i, val in enumerate(final_labels):
    val = str (val)
    if val == "":
        continue
    else:
        dmax_indices.append(i)
        
dmax_labels = []
for m in final_d:
    m = str (m)
    if m == "":
        dmax_labels.append(m)
    elif m.find("-") > 0:
        m.split("-")
        m = float (m[0])
        dmax_labels.append(m)
    else:
        m = float (m)
        dmax_labels.append(m)


In [46]:
# Process percent degradation
refined_percentage = []
for d in percent_degradation:
    d = str (d)
    d = d.replace("(n/a)", "")
    d = d.replace("N.D.", "")
    d = d.replace("nan", "")
    d = d.replace("\n", "")
    d = d.replace(">", "")
    d = d.replace("<", "")
    d = d.replace("=", "")
    refined_percentage.append(d)
    
final_percentage = []
for d in refined_percentage:
    arr = d.split('/')
    if len(arr) > 1:
        smallest_so_far = 999999
        for el in arr:
            if el == "":
                continue
            if el.find("~") > 0 or el.find("-") > 0:
                continue
            el = float(el)
            if el < smallest_so_far:
                smallest_so_far = el
        final_percentage.append(smallest_so_far)
    else:
        final_percentage.append(arr[0])
        
    
percentage_indices = []
for i, val in enumerate(final_percentage):
    val = str (val)
    if val == "":
        continue
    else:
        percentage_indices.append(i)
        
percentage_labels = []
for m in final_percentage:
    m = str (m)
    if m == "":
        percentage_labels.append(m)
    elif m.find("-") > 0:
        m.split("-")
        m = float (m[0])
        percentage_labels.append(m)
    else:
        m = float (m)
        percentage_labels.append(m)


In [54]:
# Process IC_50
refined_ic50 = []
for d in ic_50:
    d = str (d)
    d = d.replace("(n/a)", "")
    d = d.replace("N.D.", "")
    d = d.replace("nan", "")
    d = d.replace("\n", "")
    d = d.replace(">", "")
    d = d.replace("<", "")
    d = d.replace("=", "")
    refined_ic50.append(d)
    
final_ic50 = []
for d in refined_ic50:
    arr = d.split('/')
    if len(arr) > 1:
        smallest_so_far = 999999
        for el in arr:
            if el == "":
                continue
            if el.find("~") > 0 or el.find("-") > 0:
                continue
            el = float(el)
            if el < smallest_so_far:
                smallest_so_far = el
        final_ic50.append(smallest_so_far)
    else:
        final_ic50.append(arr[0])
        
ic50_indices = []
for i, val in enumerate(final_ic50):
    val = str (val)
    if val == "":
        continue
    else:
        ic50_indices.append(i)
        
ic50_labels = []
for m in final_ic50:
    m = str (m)
    if m == "":
        ic50_labels.append(m)
    elif m.find("-") > 0:
        m.split("-")
        m = float (m[0])
        ic50_labels.append(m)
    else:
        m = float (m)
        ic50_labels.append(m)
        

In [64]:
unified_labels = np.column_stack((dc50_labels, dmax_labels, percentage_labels, ic50_labels))
flags = []
for u in unified_labels:
    flag = []
    for el in u:
        if el == "":
            flag.append(0)
        else:
            flag.append(1)
    flag = np.array(flag)
    flags.append(flag)
    
flags = np.array(flags)
print(flags.shape)

(5388, 4)
[0 0 0 0]
[0 0 0 0]
[0 0 0 0]
[0 0 0 0]
[0 0 0 0]
[0 0 0 0]
[0 0 0 0]
[0 0 0 0]
[0 0 0 0]
[0 0 0 0]
[0 0 0 0]
[0 0 0 0]
[0 0 0 0]
[0 0 0 0]
[0 0 0 0]
[0 0 0 0]
[0 0 0 0]
[0 0 0 0]
[0 0 0 0]
[1 1 0 0]
[0 0 0 0]
[0 0 0 0]
[0 0 0 0]
[0 0 0 0]
[0 0 0 0]
[0 0 0 0]
[0 0 0 0]
[0 0 0 0]
[0 0 0 0]
[0 0 0 0]
[0 0 0 0]
[0 0 0 0]
[0 0 0 0]
[0 0 0 0]
[0 0 0 0]
[0 0 0 0]
[0 0 0 0]
[0 0 0 0]
[0 0 0 0]
[0 0 0 0]
[1 1 0 0]
[1 0 0 0]
[1 0 0 0]
[1 1 0 0]
[1 0 0 0]
[0 0 0 0]
[0 0 0 0]
[0 0 0 0]
[0 0 0 0]
[0 0 0 0]
[0 0 0 0]
[0 0 0 0]
[0 0 0 0]
[0 0 0 0]
[0 0 0 0]
[0 0 0 0]
[0 0 0 0]
[0 0 0 0]
[0 0 0 0]
[0 0 0 0]
[0 0 0 0]
[0 0 0 0]
[0 0 0 0]
[0 0 0 0]
[0 0 0 0]
[0 0 0 0]
[0 0 0 0]
[0 0 0 0]
[0 0 0 0]
[0 0 0 0]
[0 0 0 0]
[0 0 0 0]
[0 0 0 0]
[0 0 0 0]
[0 0 0 0]
[0 0 0 0]
[0 0 0 0]
[0 0 0 0]
[0 0 0 0]
[0 0 0 0]
[0 0 0 0]
[0 0 0 0]
[0 0 0 0]
[0 0 0 0]
[0 0 0 0]
[0 0 0 0]
[0 0 0 0]
[0 0 0 0]
[0 0 0 0]
[0 0 0 0]
[0 0 0 0]
[0 0 0 0]
[0 0 0 0]
[0 0 0 0]
[0 0 0 0]
[0 0 0 0]
[0 0 0 0]
[0 0 0 0]
[0 0 0 0]
